#app
server:
    port: 80
    
#spring
spring:
  devtools:
    restart:
      enabled: false

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: root
    password: 123456  

#logging
logging:
  config: classpath:log4j2-prod.xml

#校验crc 1:校验 0：不校验
bocon:
  checkCrc: 1
#接收端口
  port: 12345